### ISSUE TITLE
GPG error

### ISSUE THREAD

**Issue by ct2034** [omron-sinicx/ctrm#1]
When running `docker-compose build` I receive this error message:
```
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed.
```
(happending at https://github.com/omron-sinicx/ctrm/blob/0eb526345f05956fdcf6960ca2f3adc3b3772df0/Dockerfile#L5)

**Comment by yonetaniryo** [comment]
Thank you @ct2034 for noticing this and also proposing a PR!
Although NVIDIA's GPG key won't typically become an issue in docker environments as long as their base image is updated periodically, but I found that [the base image our Dockerfile refers to](https://hub.docker.com/layers/pytorch/pytorch/1.8.1-cuda10.2-cudnn7-devel/images/sha256-0bb33b2f69f2af64e1c572294e3228fa423019a17aaf9bb9428e143307f307e4) has not been updated for two years, which I believe is causing this issue. I'll check the PR you made soon. Thank you!

**Comment by yonetaniryo** [comment]
I have checked the PR #2  and confirmed it resolved the issue.
Although using a newer base image will also resolve the issue, I would like to accept #2 to keep the current base image for the reproducibility purpose. I'll merge the PR and close this issue. Thank you @ct2034 !
